AllCops:
  Include:
    - Rakefile
    - Gemfile
    - config.ru
  Exclude:
    - db/**
    - config/**
    - script/**
Documentation:
  Enabled: false
Style/DotPosition:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MultilineMethodCallIndentation:
  Enabled: false
Style/TrailingCommaInLiteral: 
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
  IgnoreClassMethods: true
Metrics/LineLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
