AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - db/**
    - config/**
    - script/**
Documentation:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/DotPosition:
  Enabled: false
Style/MultilineMethodCallIndentation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
